
GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/566ff71f-93c0-4d42-80c7-b5afdde47264

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
        "name": "Flompfffffffffffffffffffs MCinguffff",
        "status": "deadffdddffdddddfffffffffffffffff",
        "appeared": "snumpio@gmail.com",
        "url": "https://www.rd.com/wp-content/uploads/2019/05/American-shorthair-cat-scaled.jpg",
        "description": "lol"
}

###
PUT http://localhost:3000/api/users/566ff71f-93c0-4d42-80c7-b5afdde47654
Content-Type: application/json

{
    "name": "floop us",
    "email": "hiofff@gmail.com",
    "status": "alive"
}


###
DELETE http://localhost:3000/api/users/566ff71f-93c0-4d42-80c7-b5afdde47264